name: CI/CD

on:
  push:
    branches:
      - main  # or whatever your main branch is

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Install dependencies
      run: npm install

    - name: Build
      run: npm run build

    - name: Test
      run: npm test

    - name: Deploy
      run: |
        # Add your deployment script here
